projekt/Controllers/AboutsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using projekt.Data;
using projekt.Models;

namespace projekt.Views
{
    public class AboutsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AboutsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Abouts
        public async Task<IActionResult> Index()
        {
            return View(await _context.About.ToListAsync());
        }

        // GET: Abouts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var about = await _context.About
                .FirstOrDefaultAsync(m => m.Id == id);
            if (about == null)
            {
                return NotFound();
            }

            return View(about);
        }

        // GET: Abouts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Abouts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Content")] About about)
        {
            if (ModelState.IsValid)
            {
                _context.Add(about);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(about);
        }

        // GET: Abouts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var about = await _context.About.FindAsync(id);
            if (about == null)
            {
                return NotFound();
            }
            return View(about);
        }

        // POST: Abouts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Content")] About about)
        {
            if (id != about.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(about);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AboutExists(about.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(about);
        }

        // GET: Abouts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var about = await _context.About
                .FirstOrDefaultAsync(m => m.Id == id);
            if (about == null)
            {
                return NotFound();
            }

            return View(about);
        }

        // POST: Abouts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var about = await _context.About.FindAsync(id);
            _context.About.Remove(about);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AboutExists(int id)
        {
            return _context.About.Any(e => e.Id == id);
        }
    }
}

projekt/Controllers/PostsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using projekt.Data;
using projekt.Models;
using System.Drawing;
using LazZiya.ImageResize;

namespace projekt.Controllers
{
    public class PostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public PostsController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _hostEnvironment = hostEnvironment;
            _context = context;
        }

        // GET: Posts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Posts.ToListAsync());
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var posts = await _context.Posts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (posts == null)
            {
                return NotFound();
            }

            return View(posts);
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Text,ImageFile,Author")] Posts posts)
        {
            if (ModelState.IsValid)
            {
                if(posts.ImageFile != null)
                {
                    //upload file
                    string wwwRootPath = _hostEnvironment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(posts.ImageFile.FileName); //image filename
                    string extension = Path.GetExtension(posts.ImageFile.FileName);
                    fileName = fileName + DateTime.Now.ToString("yyyyMMddssff") + extension;

                    //add filename to model
                    posts.ImageName = fileName;

                    //output path
                    string path = Path.Combine(wwwRootPath + "wwwroot/images/" + fileName);

                    //move to folder
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await posts.ImageFile.CopyToAsync(fileStream);
                    }

                    //resize image
                    CreateImageFiles(fileName);

                }
                _context.Add(posts);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(posts);
        }
        //resize images
        private void CreateImageFiles(string fileName)
        {
            string wwwRootPath = _hostEnvironment.WebRootPath;

            //create thumbnail
            using(var img = Image.FromFile(Path.Combine(wwwRootPath + "wwwroot/images", fileName)))
            {
                img.Scale(800, 600).SaveAs(Path.Combine(wwwRootPath + "wwwroot/images/thumb_" + fileName));

            }
        }

        // GET: Posts/Edit/5
        
        public async Task<IActionResult> Edit(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }


            var posts = await _context.Posts.FindAsync(Id);
            if (posts == null)
            {
                return NotFound();
            }
            return View(posts);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

      /*  public async Task<IActionResult> Edit(int? id, [Bind("Id,Title,Text,ImageFile,Author")] Posts posts, IFormFile Image)
        {
            if (id != posts.Id)
            {
                return NotFound();
            }
            if (Image != null)
            {
                string ImageName = Guid.NewGuid().ToString() + Path.GetExtension(Image.FileName);

                //Get url To Save
                string SavePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", ImageName);

                posts.ImagePath = "img/" + ImageName;

                using (var stream = new FileStream(SavePath, FileMode.Create))
                {
                    Image.CopyTo(stream);
                }
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(posts);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostsExists(posts.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(posts);
        }
        */
        public async Task<IActionResult> Edit(int? Id, [Bind("Id,Title,Text,ImageName,Author")] Posts posts)
        {
            if (Id != posts.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(posts);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostsExists(posts.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
           
            return View(posts);
        } 

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var posts = await _context.Posts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (posts == null)
            {
                return NotFound();
            }

            return View(posts);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var posts = await _context.Posts.FindAsync(id);
            _context.Posts.Remove(posts);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostsExists(int id)
        {
            return _context.Posts.Any(e => e.Id == id);
        }
    }
}

projekt/Controllers/RoomsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using projekt.Data;
using projekt.Models;
using Newtonsoft.Json;
using System.Text;

namespace projekt.Controllers
{
    public class RoomsController : Controller
    {
        private readonly ApplicationDbContext _context;


        // GET: Room
        public ActionResult Index()
        {
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
            IEnumerable<Rooms> room = null;
#pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type.

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://roomapitilda.azurewebsites.net/api/Room");
                //HTTP GET
                Task<HttpResponseMessage>? responseTask = client.GetAsync("room");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<Rooms>>();
                    readTask.Wait();

                    room = readTask.Result;
                }
                else //web api sent error response 
                {
                    //log response status here..

                    room = Enumerable.Empty<Rooms>();

                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }
            return View(room);
        }


        // GET: Rooms/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rooms/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Rooms model)
        {
            using (var client = new HttpClient()) {
                client.BaseAddress = new Uri("https://roomapitilda.azurewebsites.net/api/Room");
                string data = JsonConvert.SerializeObject(model);
                StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = client.PostAsync(client.BaseAddress, content).Result;
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }

                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int Id)
        {
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.DeleteAsync("https://roomapitilda.azurewebsites.net/api/Room/" + Id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }

            return RedirectToAction("Index");
        }

    }

   
}

projekt/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - projekt</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
    <a class="headername" asp-area="" asp-controller="Home" asp-action="Index">Supreme
</a>

        <div class="headergrids2">
      <div class="mobile">
        <div class="ham" id="hamburger" onclick="hamburgermenu(this)">
          <div class="lineone"></div>
          <div class="linetwo"></div>
          <div class="linethree"></div>
        </div> 
       <!-- mobilmenyns navigering -->
         </div> 
         <div class="navi">
      <nav class="navbar">
                <ul class="nav">
                   
                       <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Abouts" asp-action="Index">About</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rooms" asp-action="Index">Rooms</a>
                        </li>

                          <!--if (SignInManager.IsSignedIn(User)) 
                        {-->
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="Index">News</a>
                        </li>
                        <!--}-->
                        
                        
                </ul>
            </nav>
            </div>
        </div>


                    
               
    </header>
    <div class="container">
        <main>
            @RenderBody()
        </main>
    </div>

    <footer>
        <h2 class="centerh2white">Hotel Supreme</h2>
        <div class="footer">
        <div class="fcontainer">
            <h3>Navigate</h3>
             <ul class="fnav">
                   
                       <li class="fnav-item">
                            <a class="fnav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="fnav-item">
                            <a class="fnav-link" asp-area="" asp-controller="Abouts" asp-action="Index">About</a>
                        </li>
                         <li class="fnav-item">
                            <a class="fnav-link" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                         <li class="fnav-item">
                            <a class="fnav-link" asp-area="" asp-controller="Rooms" asp-action="Index">Rooms</a>
                        </li>

                          <!--if (SignInManager.IsSignedIn(User)) 
                        {-->
                            <li class="fnav-item">
                            <a class="fnav-link" asp-area="" asp-controller="Posts" asp-action="Index">News</a>
                        </li>
                        <!--}-->
                        
                        
                </ul>
            <partial name="_LoginPartial" />
        </div>
        <div class="fcontainer">
            <h3>Hotel Supreme</h3>
            <a class="link" href="mailto:hotel@supreme.com">hotel@supreme.com</a><br />
            <a class="link" href="tel:08123456789">08-123456789</a>
            <p>Hotel Supreme <br />
                Supreme city 123<br />
                12345 Supreme</p>
        </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>